Tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,30 +1,76 @@
-name: example_CI
+name: CI
 
 on: [push, pull_request]
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout dépot
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
-      - name: Installer Python
+      - name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.11'
-
-      - name: Creer fichier .env
+          
+      - name: Créer fichier .env 
         run: |
-          echo "DB_HOST=localhost" >> .env
-          echo "DB_NAME=mydb" >> .env
+          echo "MYSQL_HOST=localhost" >> .env
+          echo "MONGODB_HOST=localhost" >> .env
+          echo "MYSQL_DB_NAME=mydb" >> .env
           echo "DB_USERNAME=user" >> .env
           echo "DB_PASSWORD=pass" >> .env
 
-      - name: Installer les dépendances
+      - name: Installer les dependences Python
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           pip install pytest
 
+      - name: Démarrer le conteneur
+        run: docker compose up -d
+
+      - name: Attendre MySQL
+        run: |
+          sleep 10
+          timeout=60
+          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
+            echo "Waiting for MySQL..."
+            sleep 3
+            timeout=$((timeout - 3))
+            if [ $timeout -le 0 ]; then
+              echo "MySQL failed to start"
+              exit 1
+            fi
+          done
+          sleep 5
+
+      - name: Exécuter test_user.py (TODO - inclure tous les tests)
+        working-directory: src
+        run: |
+          python3 -m pytest
+
+
+      - name: Déploiement
+        working-directory: src
+        run: echo "TODO - Faire le déploiement"
+
+      - name: Cleanup
+        if: always()
+        run: docker compose down -v
+
+
+  deploy:
+    runs-on: self-hosted
+    needs: test   # Ne se lance que si les tests passent
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Déploiement local
+        run: |
+          cd $GITHUB_WORKSPACE
+          echo "Déploiement sur la VM en cours..."
+
+          docker compose down || true
+          docker compose up -d --build      
